version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Listing files:"
      - ls -la
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Next.js app..."
      - npm run build
artifacts:
  files:
    - '**/*'
