version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "=== Current directory ==="
      - pwd
      - echo "=== Listing all files ==="
      - ls -la
      - echo "=== Checking if package.json exists ==="
      - test -f package.json && echo "package.json found" || echo "package.json NOT found"
      - echo "=== Installing dependencies ==="
      - npm install
  build:
    commands:
      - echo "=== Building Next.js app ==="
      - npm run build
artifacts:
  files:
    - '**/*'
